CREATE TABLE "countries" (
	"code" text PRIMARY KEY NOT NULL,
	"name" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "events" (
	"sport_code" text NOT NULL,
	"event_code" text NOT NULL,
	"name" text,
	"gender" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "events_sport_code_event_code_pk" PRIMARY KEY("sport_code","event_code")
);
--> statement-breakpoint
CREATE TABLE "fetch_log" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"mode" text,
	"params" jsonb,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finished_at" timestamp with time zone,
	"feed_calls" integer DEFAULT 0 NOT NULL,
	"items_seen" integer DEFAULT 0 NOT NULL,
	"rows_changed" integer DEFAULT 0 NOT NULL,
	"india_items" integer DEFAULT 0 NOT NULL,
	"errors" jsonb,
	"ok" boolean
);
--> statement-breakpoint
CREATE TABLE "india_entries" (
	"sport_code" text NOT NULL,
	"reg" text NOT NULL,
	"event_code" text NOT NULL,
	"name" text,
	"spoken_name" text,
	"gender" text,
	"type" text,
	"event_name" text,
	"is_member" boolean DEFAULT false NOT NULL,
	"sport_name" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "india_entries_sport_code_reg_event_code_pk" PRIMARY KEY("sport_code","reg","event_code")
);
--> statement-breakpoint
CREATE TABLE "india_medals" (
	"sport_code" text NOT NULL,
	"event_code" text NOT NULL,
	"competitor_key" text NOT NULL,
	"medal" text,
	"athlete_or_team" text,
	"event_name" text,
	"sport_name" text,
	"date_ist" date,
	"res_code" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"reg" text,
	"spoken_name" text,
	"members" jsonb,
	"members_spoken" text,
	"gender" text,
	"won_at" timestamp with time zone,
	"spoken_summary_en" text,
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "india_medals_sport_code_event_code_competitor_key_pk" PRIMARY KEY("sport_code","event_code","competitor_key")
);
--> statement-breakpoint
CREATE TABLE "india_results" (
	"sport_code" text NOT NULL,
	"res_code" text NOT NULL,
	"competitor_key" text NOT NULL,
	"athlete_or_team" text,
	"is_team" boolean DEFAULT false NOT NULL,
	"opponent_code" text,
	"opponent_name" text,
	"opponent_country_code" text,
	"opponent_country_name" text,
	"spoken_name" text,
	"india_score" text,
	"opponent_score" text,
	"outcome" text,
	"rank" text,
	"result_mark" text,
	"qualified" text,
	"irm" text,
	"medal" text,
	"medal_raw" text,
	"periods" jsonb,
	"spoken_summary_en" text,
	"status" text,
	"start_time" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "india_results_sport_code_res_code_competitor_key_pk" PRIMARY KEY("sport_code","res_code","competitor_key")
);
--> statement-breakpoint
CREATE TABLE "medal_standings" (
	"org_code" text PRIMARY KEY NOT NULL,
	"org_name" text,
	"rank" text,
	"gold" integer DEFAULT 0 NOT NULL,
	"silver" integer DEFAULT 0 NOT NULL,
	"bronze" integer DEFAULT 0 NOT NULL,
	"total" integer DEFAULT 0 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "schedule_items" (
	"sport_code" text NOT NULL,
	"res_code" text NOT NULL,
	"event_code" text,
	"event_name" text,
	"phase_code" text,
	"phase_name" text,
	"unit_name" text,
	"unit_name_short" text,
	"unit_num" text,
	"start_time" timestamp with time zone,
	"start_jst" text,
	"start_ist" text,
	"date_jst" date,
	"date_ist" date,
	"venue_code" text,
	"venue_name" text,
	"location_name" text,
	"status" text,
	"status_desc" text,
	"is_live" boolean DEFAULT false NOT NULL,
	"is_h2h" boolean DEFAULT false NOT NULL,
	"medal_flag" text,
	"orgs" text[] DEFAULT '{}' NOT NULL,
	"has_india" boolean DEFAULT false NOT NULL,
	"home" jsonb,
	"away" jsonb,
	"raw" jsonb,
	"first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"india_result_fetched_at" timestamp with time zone,
	"india_entered" boolean DEFAULT false NOT NULL,
	"short_id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "schedule_items_short_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1000 CACHE 1),
	CONSTRAINT "schedule_items_sport_code_res_code_pk" PRIMARY KEY("sport_code","res_code")
);
--> statement-breakpoint
CREATE TABLE "sports" (
	"code" text PRIMARY KEY NOT NULL,
	"name" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "idx_india_entries_event" ON "india_entries" USING btree ("sport_code","event_code");--> statement-breakpoint
CREATE INDEX "idx_india_results_updated" ON "india_results" USING btree ("updated_at");--> statement-breakpoint
CREATE INDEX "idx_india_results_start" ON "india_results" USING btree ("start_time");--> statement-breakpoint
CREATE INDEX "idx_india_results_sport_res" ON "india_results" USING btree ("sport_code","res_code");--> statement-breakpoint
CREATE INDEX "idx_india_results_res" ON "india_results" USING btree ("res_code");--> statement-breakpoint
CREATE INDEX "idx_schedule_items_date_jst" ON "schedule_items" USING btree ("date_jst");--> statement-breakpoint
CREATE INDEX "idx_schedule_items_date_ist" ON "schedule_items" USING btree ("date_ist");--> statement-breakpoint
CREATE INDEX "idx_schedule_items_has_india" ON "schedule_items" USING btree ("has_india");--> statement-breakpoint
CREATE INDEX "idx_schedule_items_status" ON "schedule_items" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_schedule_items_sport_code" ON "schedule_items" USING btree ("sport_code");--> statement-breakpoint
CREATE INDEX "idx_schedule_items_india_entered" ON "schedule_items" USING btree ("india_entered");--> statement-breakpoint
CREATE INDEX "idx_schedule_items_event" ON "schedule_items" USING btree ("sport_code","event_code");--> statement-breakpoint
CREATE INDEX "idx_schedule_items_start_time" ON "schedule_items" USING btree ("start_time");--> statement-breakpoint
CREATE INDEX "idx_schedule_items_india_date" ON "schedule_items" USING btree ("has_india","date_ist");--> statement-breakpoint
CREATE INDEX "idx_schedule_items_india_start" ON "schedule_items" USING btree ("has_india","start_time");--> statement-breakpoint
CREATE INDEX "idx_schedule_items_live" ON "schedule_items" USING btree ("is_live");--> statement-breakpoint
CREATE UNIQUE INDEX "schedule_items_short_id_key" ON "schedule_items" USING btree ("short_id");