/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MedalsRouteImport } from './routes/medals'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StatusRouteImport } from './routes/status'
import { Route as AthleteRegRouteImport } from './routes/athlete.$reg'
import { Route as ScheduleIndexRouteImport } from './routes/schedule.index'
import { Route as ScheduleDateRouteImport } from './routes/schedule.$date'
import { Route as SportsIndexRouteImport } from './routes/sports.index'
import { Route as SportsSportCodeRouteImport } from './routes/sports.$sportCode'
import { Route as ApiPublicFeedTestRouteImport } from './routes/api/public/feed-test'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicStatusCheckRouteImport } from './routes/api/public/status-check'
import { Route as ApiPublicStatusDataRouteImport } from './routes/api/public/status-data'
import { Route as ApiPublicVoiceConfigRouteImport } from './routes/api/public/voice-config'
import { Route as MatchSportCodeResCodeRouteImport } from './routes/match.$sportCode.$resCode'
import { Route as ApiPublicAgentSplatRouteImport } from './routes/api/public/agent/$'
import { Route as ApiPublicAppSplatRouteImport } from './routes/api/public/app/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedalsRoute = MedalsRouteImport.update({
  id: '/medals',
  path: '/medals',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteRegRoute = AthleteRegRouteImport.update({
  id: '/athlete/$reg',
  path: '/athlete/$reg',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleDateRoute = ScheduleDateRouteImport.update({
  id: '/schedule/$date',
  path: '/schedule/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsIndexRoute = SportsIndexRouteImport.update({
  id: '/sports/',
  path: '/sports/',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsSportCodeRoute = SportsSportCodeRouteImport.update({
  id: '/sports/$sportCode',
  path: '/sports/$sportCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedTestRoute = ApiPublicFeedTestRouteImport.update({
  id: '/api/public/feed-test',
  path: '/api/public/feed-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStatusCheckRoute = ApiPublicStatusCheckRouteImport.update({
  id: '/api/public/status-check',
  path: '/api/public/status-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStatusDataRoute = ApiPublicStatusDataRouteImport.update({
  id: '/api/public/status-data',
  path: '/api/public/status-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVoiceConfigRoute = ApiPublicVoiceConfigRouteImport.update({
  id: '/api/public/voice-config',
  path: '/api/public/voice-config',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchSportCodeResCodeRoute = MatchSportCodeResCodeRouteImport.update({
  id: '/match/$sportCode/$resCode',
  path: '/match/$sportCode/$resCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentSplatRoute = ApiPublicAgentSplatRouteImport.update({
  id: '/api/public/agent/$',
  path: '/api/public/agent/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppSplatRoute = ApiPublicAppSplatRouteImport.update({
  id: '/api/public/app/$',
  path: '/api/public/app/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/medals': typeof MedalsRoute
  '/search': typeof SearchRoute
  '/status': typeof StatusRoute
  '/athlete/$reg': typeof AthleteRegRoute
  '/schedule/$date': typeof ScheduleDateRoute
  '/sports/$sportCode': typeof SportsSportCodeRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/sports/': typeof SportsIndexRoute
  '/api/public/feed-test': typeof ApiPublicFeedTestRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/status-check': typeof ApiPublicStatusCheckRoute
  '/api/public/status-data': typeof ApiPublicStatusDataRoute
  '/api/public/voice-config': typeof ApiPublicVoiceConfigRoute
  '/match/$sportCode/$resCode': typeof MatchSportCodeResCodeRoute
  '/api/public/agent/$': typeof ApiPublicAgentSplatRoute
  '/api/public/app/$': typeof ApiPublicAppSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/medals': typeof MedalsRoute
  '/search': typeof SearchRoute
  '/status': typeof StatusRoute
  '/athlete/$reg': typeof AthleteRegRoute
  '/schedule/$date': typeof ScheduleDateRoute
  '/sports/$sportCode': typeof SportsSportCodeRoute
  '/schedule': typeof ScheduleIndexRoute
  '/sports': typeof SportsIndexRoute
  '/api/public/feed-test': typeof ApiPublicFeedTestRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/status-check': typeof ApiPublicStatusCheckRoute
  '/api/public/status-data': typeof ApiPublicStatusDataRoute
  '/api/public/voice-config': typeof ApiPublicVoiceConfigRoute
  '/match/$sportCode/$resCode': typeof MatchSportCodeResCodeRoute
  '/api/public/agent/$': typeof ApiPublicAgentSplatRoute
  '/api/public/app/$': typeof ApiPublicAppSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/medals': typeof MedalsRoute
  '/search': typeof SearchRoute
  '/status': typeof StatusRoute
  '/athlete/$reg': typeof AthleteRegRoute
  '/schedule/$date': typeof ScheduleDateRoute
  '/sports/$sportCode': typeof SportsSportCodeRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/sports/': typeof SportsIndexRoute
  '/api/public/feed-test': typeof ApiPublicFeedTestRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/status-check': typeof ApiPublicStatusCheckRoute
  '/api/public/status-data': typeof ApiPublicStatusDataRoute
  '/api/public/voice-config': typeof ApiPublicVoiceConfigRoute
  '/match/$sportCode/$resCode': typeof MatchSportCodeResCodeRoute
  '/api/public/agent/$': typeof ApiPublicAgentSplatRoute
  '/api/public/app/$': typeof ApiPublicAppSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/medals'
    | '/search'
    | '/status'
    | '/athlete/$reg'
    | '/schedule/$date'
    | '/sports/$sportCode'
    | '/schedule/'
    | '/sports/'
    | '/api/public/feed-test'
    | '/api/public/ingest'
    | '/api/public/status-check'
    | '/api/public/status-data'
    | '/api/public/voice-config'
    | '/match/$sportCode/$resCode'
    | '/api/public/agent/$'
    | '/api/public/app/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/medals'
    | '/search'
    | '/status'
    | '/athlete/$reg'
    | '/schedule/$date'
    | '/sports/$sportCode'
    | '/schedule'
    | '/sports'
    | '/api/public/feed-test'
    | '/api/public/ingest'
    | '/api/public/status-check'
    | '/api/public/status-data'
    | '/api/public/voice-config'
    | '/match/$sportCode/$resCode'
    | '/api/public/agent/$'
    | '/api/public/app/$'
  id:
    | '__root__'
    | '/'
    | '/medals'
    | '/search'
    | '/status'
    | '/athlete/$reg'
    | '/schedule/$date'
    | '/sports/$sportCode'
    | '/schedule/'
    | '/sports/'
    | '/api/public/feed-test'
    | '/api/public/ingest'
    | '/api/public/status-check'
    | '/api/public/status-data'
    | '/api/public/voice-config'
    | '/match/$sportCode/$resCode'
    | '/api/public/agent/$'
    | '/api/public/app/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MedalsRoute: typeof MedalsRoute
  SearchRoute: typeof SearchRoute
  StatusRoute: typeof StatusRoute
  AthleteRegRoute: typeof AthleteRegRoute
  ScheduleDateRoute: typeof ScheduleDateRoute
  SportsSportCodeRoute: typeof SportsSportCodeRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  SportsIndexRoute: typeof SportsIndexRoute
  ApiPublicFeedTestRoute: typeof ApiPublicFeedTestRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicStatusCheckRoute: typeof ApiPublicStatusCheckRoute
  ApiPublicStatusDataRoute: typeof ApiPublicStatusDataRoute
  ApiPublicVoiceConfigRoute: typeof ApiPublicVoiceConfigRoute
  MatchSportCodeResCodeRoute: typeof MatchSportCodeResCodeRoute
  ApiPublicAgentSplatRoute: typeof ApiPublicAgentSplatRoute
  ApiPublicAppSplatRoute: typeof ApiPublicAppSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medals': {
      id: '/medals'
      path: '/medals'
      fullPath: '/medals'
      preLoaderRoute: typeof MedalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/$reg': {
      id: '/athlete/$reg'
      path: '/athlete/$reg'
      fullPath: '/athlete/$reg'
      preLoaderRoute: typeof AthleteRegRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/$date': {
      id: '/schedule/$date'
      path: '/schedule/$date'
      fullPath: '/schedule/$date'
      preLoaderRoute: typeof ScheduleDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/': {
      id: '/sports/'
      path: '/sports'
      fullPath: '/sports/'
      preLoaderRoute: typeof SportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/$sportCode': {
      id: '/sports/$sportCode'
      path: '/sports/$sportCode'
      fullPath: '/sports/$sportCode'
      preLoaderRoute: typeof SportsSportCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feed-test': {
      id: '/api/public/feed-test'
      path: '/api/public/feed-test'
      fullPath: '/api/public/feed-test'
      preLoaderRoute: typeof ApiPublicFeedTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/status-check': {
      id: '/api/public/status-check'
      path: '/api/public/status-check'
      fullPath: '/api/public/status-check'
      preLoaderRoute: typeof ApiPublicStatusCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/status-data': {
      id: '/api/public/status-data'
      path: '/api/public/status-data'
      fullPath: '/api/public/status-data'
      preLoaderRoute: typeof ApiPublicStatusDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice-config': {
      id: '/api/public/voice-config'
      path: '/api/public/voice-config'
      fullPath: '/api/public/voice-config'
      preLoaderRoute: typeof ApiPublicVoiceConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$sportCode/$resCode': {
      id: '/match/$sportCode/$resCode'
      path: '/match/$sportCode/$resCode'
      fullPath: '/match/$sportCode/$resCode'
      preLoaderRoute: typeof MatchSportCodeResCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/$': {
      id: '/api/public/agent/$'
      path: '/api/public/agent/$'
      fullPath: '/api/public/agent/$'
      preLoaderRoute: typeof ApiPublicAgentSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/app/$': {
      id: '/api/public/app/$'
      path: '/api/public/app/$'
      fullPath: '/api/public/app/$'
      preLoaderRoute: typeof ApiPublicAppSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MedalsRoute: MedalsRoute,
  SearchRoute: SearchRoute,
  StatusRoute: StatusRoute,
  AthleteRegRoute: AthleteRegRoute,
  ScheduleDateRoute: ScheduleDateRoute,
  SportsSportCodeRoute: SportsSportCodeRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  SportsIndexRoute: SportsIndexRoute,
  ApiPublicFeedTestRoute: ApiPublicFeedTestRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicStatusCheckRoute: ApiPublicStatusCheckRoute,
  ApiPublicStatusDataRoute: ApiPublicStatusDataRoute,
  ApiPublicVoiceConfigRoute: ApiPublicVoiceConfigRoute,
  MatchSportCodeResCodeRoute: MatchSportCodeResCodeRoute,
  ApiPublicAgentSplatRoute: ApiPublicAgentSplatRoute,
  ApiPublicAppSplatRoute: ApiPublicAppSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
